name: calculadora_imp_met
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  keyboard_actions: ^3.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/output-onlinepngtools.png"
  adaptive_icon_background: "assets/icons/output-onlinepngtools.png"
  remove_alpha_ios: true


flutter:
 
  uses-material-design: true

  assets:
    - assets/icons/output-onlinepngtools.png
    - assets/icons/fonts/CustomIcons.ttf
    - assets/images/loading.gif
    - assets/images/logo_imp_500_x_550.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/fonts/CustomIcons.ttf
          weight: 400
          style: normal
        - asset: assets/icons/fonts/CustomIcons.ttf
          weight: 700
          style: normal
